stages:
- build

variables:
  CONTAINER_RELEASE_IMAGE: registry.c0.az01.sandmanbb.com/$CI_PROJECT_PATH:$CI_COMMIT_TAG

before_script:
  - echo $CONTAINER_RELEASE_IMAGE
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD registry.c0.az01.sandmanbb.com

build:
  stage: build
  only:
    - tags
  script:
    - docker-compose -f docker-compose.yml build 
    - docker-compose -f docker-compose.yml push
  tags:
    - az-sandman-01